### ISSUE TITLE
Rating bar invisible in angular 17

### ISSUE THREAD

**Issue by tim-gromeyer** [MurhafSousli/ngx-bar-rating#109]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?

Rating bar visible

#### What is the current behavior?

The rating bar is not visible, no matter what I do. I checked it, the rating-bar tag exists in the site html and takes up space, but nothing is there. It's also not hidden by some css.

#### What are the steps to reproduce?

Idk if it's specific to my site, but just using it normally like documented should be enough and you see nothing.

#### Which versions are you using for the following packages?

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1703.3
@angular-devkit/build-angular   17.3.3
@angular-devkit/core            17.3.3
@angular-devkit/schematics      17.3.3
@angular/cdk                    17.3.3
@angular/cli                    17.3.3
@angular/material               17.3.3
@schematics/angular             17.3.3
rxjs                            7.8.1
typescript                      5.3.3
zone.js                         0.14.4
ngx-bar-rating: 6.0.0

#### Is there anything else we should know?

That's my first angular project ever, so it might be something on my side. I can provide the full source code if you want to

**Comment by MurhafSousli** [comment]
Need to investigate, for now it seems to works when a star template is used https://stackblitz.com/edit/ngx-bar-rating-ng17

**Comment by MurhafSousli** [comment]
You haven't imported a theme, that's why the component was invisible.

**Comment by tim-gromeyer** [comment]
Ups, my bad. How can I import a theme?
