### ISSUE TITLE
on change `max` variable count, UI is not updating

### ISSUE THREAD

**Issue by gaurav341** [MurhafSousli/ngx-bar-rating#11]
When I change `max` variable dynamically, star on UI is not updating, 

but hovering over the star, it updates.
[plnkr](https://plnkr.co/edit/FQ0NjG?p=preview)

**Comment by MurhafSousli** [comment]
@gaurav341 That's not possible with the current implementation, but there is a workaround, here is [plnkr](https://plnkr.co/edit/EnkUFA?p=preview)
