### ISSUE TITLE
two instances on same page with different css

### ISSUE THREAD

**Issue by vladanPro** [MurhafSousli/ngx-bar-rating#12]
I wonder can i have on same page two different <bar-rating> instances and with different CSS , i would use one just to read only and other in modal windows to rate. Thank you.

**Comment by MurhafSousli** [comment]
@vladanPro For different themes, use the `[theme]` input 

```html
<bar-rating [(rate)]="horiRate" [max]="10" [theme]="'horizontal'" [showText]="true"></bar-rating>

<bar-rating [(rate)]="squareRate" [max]="5" [theme]="'square'"></bar-rating>
```
If you mean 2 instances with the same theme but different CSS, then use CSS!

```html
<bar-rating id="rating1" [(rate)]="ratingOne" [max]="5" [theme]="'square'"></bar-rating>

<bar-rating id="rating2" [(rate)]="ratingTwo" [max]="5" [theme]="'square'"></bar-rating>
```
```scss
#rating1 {
   // custom style goes here
}

#rating2 {
   // custom style goes here
}
```

**Comment by vladanPro** [comment]
Its working, my problem was how to show rate in other instance , so i see just [(rate)] and replace variable. Thank you.

**Comment by MurhafSousli** [comment]
Welcome!
