### ISSUE TITLE
is it possible to give an actual star rating value ?

### ISSUE THREAD

**Issue by NorhanSamir** [MurhafSousli/ngx-bar-rating#13]

**Comment by MurhafSousli** [comment]
Yes, indeed
```html
<bar-rating [rate]="3" [max]="5"></bar-rating>
```

**Comment by NorhanSamir** [comment]
I want to make the value of each star is 2 not 1 as the star rating will be 10 and number of the stars are 5  is it possible ?

**Comment by MurhafSousli** [comment]
No, but you can easily define this logic from your component!
