### ISSUE TITLE
Stars not visible

### ISSUE THREAD

**Issue by abhilashfancy** [MurhafSousli/ngx-bar-rating#14]
I have implemented everything as mentioned in the readme but nothing is visible. It leaves empty space instead of stars.

**Comment by MurhafSousli** [comment]
It depends on which stars you are trying to use, e.g. for font awesome stars stylesheet, add your full code so I can help you

**Comment by MurhafSousli** [comment]
@barabasishe Have a look at this [stackblitz](https://stackblitz.com/edit/ngx-bar-rating?file=app%2Fapp.component.html)

By the way, you don't need to import the default theme unless you want the stars theme.

**Comment by HugoCastelani** [comment]
@MurhafSousli But isn't stars theme the default one? In my project and also at this stackblitz project you sent, the default rating bar appears only when the default theme import is made.

**Comment by MurhafSousli** [comment]
@HugoCastelani Sure the default stars requires the default theme!

**Comment by HugoCastelani** [comment]
"By the way, you don't need to import the default theme unless you want the stars theme.".
Stars theme in my interpretation: br-stars-theme.
What I understood at all: I don't need to import br-default-theme to use the rating bar without specifying a theme. E.g.:

`<bar-rating [(rate)]="rate" [max]="5"></bar-rating>`

In the case above I would not need any import. That's what I got from what you said. If I misunderstood, sorry, but if I didn't, then there's not any case that I would not need to import anything, since the situation above also requires br-default-theme import.

**Comment by MurhafSousli** [comment]
@HugoCastelani My answer was in the context of his usage

> ```
>  @import '~ngx-bar-rating/themes/br-default-theme.css'; 
>  @import '~ngx-bar-rating/themes/br-horizontal-theme.css';
> ```

I told him that he does not need to import both themes!

**Comment by HugoCastelani** [comment]
Oh, OK.

**Comment by MizaN13** [comment]
> It depends on which stars you are trying to use, e.g. for font awesome stars stylesheet, add your usage code so I can help you

@MurhafSousli  Can you please help me with fontawesome starratig?

**Comment by MizaN13** [comment]
> It depends on which stars you are trying to use, e.g. for font awesome stars stylesheet, add your usage code so I can help you



> > It depends on which stars you are trying to use, e.g. for font awesome stars stylesheet, add your usage code so I can help you
> 
> @MurhafSousli Can you please help me with fontawesome starrating?

Here I got my expected code. https://www.c-sharpcorner.com/article/star-rating-in-angular-5/

**Comment by ahmadshakeel78** [comment]
Property 'rate' does not exist
any one facing this issue ?
any help plesae

**Comment by aamirsultanmalik** [comment]
if i implement in my existing project the stars doesn't show up and if i implement it in new project then is get 
Property 'cssRate' does not exist
Property 'faRate' does not exist
any clues?

**Comment by abhigautamvvdn** [comment]
There is some issue with the stars, It is not appearing on the UI although  I followed the same steps as mentioned in the npm link.

**Comment by MurhafSousli** [comment]
It is better to reproduce your issue in a stackblitz and open a new issue, thats the best way to get help

**Comment by adnanrafique** [comment]
I my case, styles were not being imported correctly. I added the styles in my angular.json and now it is working fine.

`"styles": [
              "node_modules/ngx-bar-rating/themes/br-default-theme.scss",
              "src/styles.css"
            ],`
