### ISSUE TITLE
Update the rating from the backend

### ISSUE THREAD

**Issue by Octavious** [MurhafSousli/ngx-bar-rating#16]
Hello,

thanks for the great component, i am new to Angular so i am not sure if this is really an issue or a question how it can be done.

i have a page which has several items which need rating (list of items), what i do:
1. loop through the items with *ngfor
2. i link the inital rating coming from the model (DB) to the bar rating item:
<bar-rating [(rate)]="item.rate" [max]="5" (rateChange)="changeRate($event, item.rate, item.id)"></bar-rating>
3. in the function changeRate, i check if the client already voted (using a cookie).
4. if he already voted i will not count his vote, and the stars should show the intial rating
5. if it is a new vote, i calculate the new rate and apply it.

Point 4 is the tricky one, it seems that upon click, stars (and hence the model) is already updated.

is there away to catch the event before stars are updated and decide if the update shall proceed or not?
or get the previous rating value alongside the current value

or maybe it is simply i am ignorant and doing it wrongly.

Thanks again for the great component

**Comment by MurhafSousli** [comment]
If a user has already voted then the component should be disabled, use `[disabled]` input in this case.

**Comment by Octavious** [comment]
Thank you

It will solve the issue if already voted. 

Just a quick question, if he didn't vote, and I want to show the new rate (not the user vote itself), then I have to handle it in my model I guess.. Not through the component, correct? 

May I suggest that in the future, the component gives back the original value and the vote rate value in the event [rateChange], it will make life much easier :) 

Thanks for your reply

**Comment by MurhafSousli** [comment]
First you rate value is bound to your service, when user rate, it will show him his rate and the output will emit, on that emit you update the rate using your service

```html
<bar-rating [rate]="model.rate" (rateChange)="updateRate($event, model.id)"></bar-rating>
```
```ts
updateRate(value, id) {
   myService.updateRate(id, value);
}
```
When the model is updated it will update the component will the total rate

**Comment by Octavious** [comment]
i will do it that way

Thanks Murhaf

**Comment by MurhafSousli** [comment]
I think it is better to have an option to manually update the rate

**Comment by Octavious** [comment]
actually, i am trying to update the model to apply new rate, it seems it works only for the first time:
https://plnkr.co/edit/3GSfiO70Dq1Ghsn48cWw?p=preview

check the star rating

and sorry for annoying

**Comment by Octavious** [comment]
@MurhafSousli: i guess it is becoming to advanced for me :)

i have more than one component (doing ngfor to loop over them), and doing little search suggested that i need to use @ViewChildren, still, i dont seem to be able to get a handle to the particular one which fired the event.
