### ISSUE TITLE
Decimal ratings wont work

### ISSUE THREAD

**Issue by sskhokhar** [MurhafSousli/ngx-bar-rating#17]
Hi,
Ratings provided in decimals wont work. It gets only the integral part of a number e.g 3.5 will be shown as 3 stars not 3 and half star

**Comment by MurhafSousli** [comment]
Did you try 3.6?

**Comment by sskhokhar** [comment]
@MurhafSousli  Yes indeed I have tried but it still not worked.
![capture](https://user-images.githubusercontent.com/13753852/39206941-28ceda84-4818-11e8-965d-215bbedefa6c.PNG)
![capture](https://user-images.githubusercontent.com/13753852/39206957-37c0da92-4818-11e8-8b03-783775a3514f.PNG)
Here are the screenshots

**Comment by MurhafSousli** [comment]
Use `fontawesome-o` theme instead, check this [live stackblitz](https://stackblitz.com/edit/ngx-bar-rating-dj6gxr?file=app%2Fapp.component.html)

**Comment by raykrai** [comment]
Not working. Even download the live stackblitz example, stars even't appear...

**Comment by yardenhod** [comment]
> Not working. Even downloading the live stackblitz example, stars doesn't appear...

You need to use `fontawesome-o` theme and **add FontAwesome font to your project**

**Comment by tayambamwanza** [comment]
@MurhafSousli please indicate that fontawesome-o theme is the one with the fractional stars in documentation, as well as the fact that for older versions one will need to use fontawesome 4 and not 5  :), I was having this same issue, if I knew this earlier would've saved a lot of time. Thank you so much for your time on this btw, I will star.

**Comment by MurhafSousli** [comment]
@tayambamwanza Thanks for the star!

In v3.0.0, The font awesome themes have been removed in favour of using the custom templates
