### ISSUE TITLE
Font Awesome doesn't loading

### ISSUE THREAD

**Issue by MaciejWWojcik** [MurhafSousli/ngx-bar-rating#18]
Hello,
I want to use your ngx-bar-rating with font awesome. So I tried to add this as you wrote in readme, but this doesn't working correctly. Bar Rating component appears, and works I mean I can click on this and get value, but there is no icons on bar.

I added in styles.scss this:
`@import '~ngx-bar-rating/themes/br-fontawesome-theme';`

Next in my component I have this:
`  <bar-rating name="rating" [theme]="'fontawesome'" [formControl]="form.controls['rate']" [max]="3" required></bar-rating>`

When I run this I receive something like this:
[screen](https://i.imgur.com/RNQcszR.png)

In dev console all styles looks ok for me:
[screens from console](https://imgur.com/a/1MwfI97)

Do you have any idea what's happening?

**Comment by MurhafSousli** [comment]
@MaciejWWojcik Check this [staclblitz](https://stackblitz.com/edit/ngx-bar-rating-dj6gxr?file=app%2Fapp.component.html), note that the FontAwsome is 4 imported, 5 is not supported out of the box
