### ISSUE TITLE
Default class is overwriting

### ISSUE THREAD

**Issue by Urvashi2707** [MurhafSousli/ngx-bar-rating#26]
<img width="1410" alt="screen shot 2018-07-28 at 5 45 38 pm" src="https://user-images.githubusercontent.com/29358439/43356420-1878ad98-928e-11e8-82fe-5c81b5366f4a.png">

Hi,
I am using ngx-bar-rating square theme.But somehow Default class is getting created because of which square with star is showing up .

         <ng-template ngbPanelContent>
                                <div class=".col-xs">
                                    <nb-card class=".col-xs" class=".space">
                                        <nb-card-body>
                                            <table style="width: 80%;">
                                                <tbody>
                                                    <tr *ngFor="let f of feedback" class="question">
                                                        <td>{{f.questions}}</td>
                                                        <td><bar-rating [rate]="f.rating" [max]="5" class="br br-square" [readOnly]="true" style="float: right;"></bar-rating></td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </nb-card-body>
                                    </nb-card>
                                </div>
                            </ng-template>

**Comment by MurhafSousli** [comment]
You shouldn't use the class to set the theme, just use the `theme` input instead.
