### ISSUE TITLE
Add Material Icons theme

### ISSUE THREAD

**Issue by odahcam** [MurhafSousli/ngx-bar-rating#30]
This is a **feature request**.

I would like to see a [Material Icons](https://material.io/icons) theme in this lovely package. :)

It would be nice to use with Angular Material.

**Comment by MurhafSousli** [comment]
We can't add extra dependencies to the plugin, this can become possible with a new version that allows embedding custom template.

**Comment by odahcam** [comment]
Are Bootstrap or Font-awesome extra dependencies or in my final bundle? If they are that's a problem, if they aren't I can say that Material Icons work the same way.
