### ISSUE TITLE
Enable component style importing support

### ISSUE THREAD

**Issue by odahcam** [MurhafSousli/ngx-bar-rating#31]
It is not nice to have to import themes in the global scope (styles.scss or index.html).

**Comment by odahcam** [comment]
Why close? 👀

**Comment by MurhafSousli** [comment]
@odahcam It seems my first comment haven't been posted!
Ofcourse, you have to import it from the global styles, then how do you give the users the option to import a theme?

**Comment by odahcam** [comment]
The plugin itself could manage its theme's imports.

**Comment by MurhafSousli** [comment]
No, This mean all the themes will be included even if you do not use them, increases the bundle size

**Comment by odahcam** [comment]
Not if you lazy-load them, https://material.angular.io does that.
