### ISSUE TITLE
Form Validation

### ISSUE THREAD

**Issue by jkirkerx** [MurhafSousli/ngx-bar-rating#35]
Nice control!
Took awhile for me to understand how to get font awesome 4.7.2 to work with it and wrote a new CSS file for it. 

But my final issue is with form validation using reactive form and Angular 6.1.10. When I select the rating it triggers the form to be valid when it's not. I looked at the source last Friday to see if I could isolate it but wasn't able to. Triple checked my form validation code as well.

Maybe you can look into this. I would post code but I don't think that will help at the moment unless you ask.

**Comment by MurhafSousli** [comment]
Sorry, I was inactive on this project for a long time, reopen if you still use the project and have the same issue.
