### ISSUE TITLE
Font-Awesome CSS for 4.7.2

### ISSUE THREAD

**Issue by jkirkerx** [MurhafSousli/ngx-bar-rating#37]
This took me hours to figure out, because Font-Awesome changed the way they use CSS. But on version 4.7.2, the last free version using solid, brand and regular, the provided examples didn't work. I created 4 of these to represent different sizes just like fa-2x, fa-4x, in which below is the large size. I renamed it scss so I can use it in my Angular 6.1.10 project but I haven't any variables yet. Still being tested but works fine.
The problem was with the font family name and :after not rendering anything. I changed it to :before

Just wanted to contribute in case someone else has the problem. So It's not an issue.

br-fontawesome-4X.scss

<pre>
.br-fontawesome .br-units {
    align-items: center
}

.br-fontawesome .br-unit {
    font: normal normal normal 60px/1 FontAwesome;
    font-family: 'Font Awesome 5 Free';    
    font-size: 4rem;
    font-weight: 900;
    text-rendering: auto;
    -webkit-font-smoothing: antialiased;
    text-decoration: none;
    margin-right: 2px
}

.br-fontawesome .br-unit:before {
    content: '\f005';
    color: #d2d2d2
}

.br-fontawesome .br-selected:before {
    font-family: 'Font Awesome 5 Free';
    color: #ffdf00
}

.br-fontawesome .br-active:before {
    color: #ffdf00
}
</pre>

**Comment by MurhafSousli** [comment]
In v3.0.0, custom template solves the issue with the latest FontAwesome
