### ISSUE TITLE
clicking one bar rating selects all other bar ratings in a list

### ISSUE THREAD

**Issue by aravindnaidu09** [MurhafSousli/ngx-bar-rating#39]
Hi,

I've bar rating in my component and I've have a list of bar-rating in my component. selecting one bar rating selects all other bar rating automatically. need solution for this. my code is 
template:  <div class="row m-1 p-2" *ngFor="let item of detailItems; let index">
        <div class="col-lg-8 border-bottom">{{ item }}</div>
        <div class="col-lg-4 border-bottom">
          <bar-rating
            class="rating"
            [(rate)]="rate"
            [max]="5"
            [theme]="'stars'"
            [showText]="true"
            [titles]="['one', 'two', 'three', 'four', 'five']"
            (rateChange)="onRatingChange()"
          ></bar-rating>
          
        </div>
      </div>

and in .ts file I've used 
public rate: number = 0;

Thanks

**Comment by anshul0430** [comment]
Same issue

**Comment by likhit-vivek** [comment]
@aravindnaidu09 You are two-way binding the same variable called 'rate' for all bar ratings. So, clicking on one bar rating will change 'rate' and that'll in turn change all the other bar ratings. So you should use a different variable for every bar rating.
@MurhafSousli

**Comment by hatemgh123** [comment]
@likhit-vivek  thx it's work for me
