### ISSUE TITLE
couldn't bind to disabled property. Not found disabled property

### ISSUE THREAD

**Issue by Togtokhb** [MurhafSousli/ngx-bar-rating#40]

**Comment by asabaki** [comment]
I also encountered this issue.

**Comment by khairnaraksh** [comment]
i Also found this issue.

**Comment by usman125** [comment]
a work around can be used to achieve the disable functionality using css3 with following example:-

<div class="admin-controls">
<bar-rating [(rate)]="rating" [max]="max"></bar-rating>
</div>

.admin-controls bar-rating{
  pointer-events: none;
}
the above examples work fine with me achieved what i wanted.

Thanks,

**Comment by MurhafSousli** [comment]
The disabled should be added when it is acting as a form control, try to place it in an angular form

**Comment by MurhafSousli** [comment]
If you are not using the component inside angular form, the disabled will not work. in this case, use `[readOnly]` input instead.
