### ISSUE TITLE
Customize "br" margin

### ISSUE THREAD

**Issue by mayaizart** [MurhafSousli/ngx-bar-rating#43]
Hey, I've created by own theme, but there is a margin of 15px above and below the rating element. I saw that it's defined here: https://github.com/MurhafSousli/ngx-bar-rating/blob/53af77e9a25f0ee248c2027b997364f9fadc72f8/src/component/bar-rating.component.scss#L5-L8
Is it in any way to override/change it?
Thanks :)

**Comment by lippomano** [comment]
yes the margin is not always necessary
@mayaizart how did you override it?

**Comment by daniellopezj01** [comment]
hello can you solution this bus?

**Comment by daniellopezj01** [comment]
hello after search different solution. this bug is solved aply in your principal  **styles.css**
```
.br {
    display: initial;
}
```
if you select theme you can overwrite this in your principal **styles.css**
this solution is applied in angular 9.

I hope I can help you :)

**Comment by niraz100** [comment]
::ng-deep .br {
  margin: 0 !important;
}

**Comment by niraz100** [comment]
::ng-deep .br {
  margin: 0 !important;
}

**Comment by MurhafSousli** [comment]
The margin will be removed in v3.0.0
