### ISSUE TITLE
[rate] decimal

### ISSUE THREAD

**Issue by daniellopezj01** [MurhafSousli/ngx-bar-rating#47]
<bar-rating [(rate)]="cssRate" **[rate]="4.5"** [wholeStars]="true" [readOnly]="true" [max]="5"></bar-rating>
            
this works corrently, but not paint half star. can you check please

**Comment by brankoiliccc** [comment]
This seems to be working only for fontawesome-o theme

https://github.com/MurhafSousli/ngx-bar-rating/issues/21

You can test it in stackblitz provided in issue 21 by changing theme 

https://github.com/MurhafSousli/ngx-bar-rating/commit/21d970fe4a21a385998851b6fe2056d0e9c0f140#diff-f2f80621dccadf879f3301cf1f80672a

**Comment by MurhafSousli** [comment]
@brankoiliccc is correct, closing...
