### ISSUE TITLE
'bar-rating' is not a known element, Angular 9

### ISSUE THREAD

**Issue by tryn0** [MurhafSousli/ngx-bar-rating#52]
Hi, I have followed the README file to install it, but when show it 
through the HTML file it give me an error:
`'bar-rating' is not a known element:
1. If 'bar-rating' is an Angular component, then verify that it is part of this module.
2. If 'bar-rating' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.ng`

I have added it in app.module.ts and imports section, any small help?
Sorry for my english.

**Comment by MurhafSousli** [comment]
Please try the latest version 2.0.0!
