### ISSUE TITLE
Error not compatible with Angular Ivy

### ISSUE THREAD

**Issue by Bousseta** [MurhafSousli/ngx-bar-rating#53]
run on Angular 10 
![image](https://user-images.githubusercontent.com/39128029/86022137-da74db80-ba21-11ea-9c22-fc5656ed84b7.png)

**Comment by mic8** [comment]
Is there any updates for this issue?

**Comment by MurhafSousli** [comment]
Unfortunately, I am not updating this module anytime soon, consider using the source directly in your project

**Comment by parth181195** [comment]
is it ok if i send pr for ivy will u merge it
