### ISSUE TITLE
Angular 11

### ISSUE THREAD

**Issue by hmmmmniek** [MurhafSousli/ngx-bar-rating#60]
#### I am submitting a

- [x] Feature Request

#### Description
Getting this error because the ngx-bar-rating uses angular 10. 
Using `npm install --legacy-peer-deps` works fine. But of course would be nice to just have this up to date :)
```
npm ERR! Found: @angular/common@11.0.6
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^11.0.4" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.1.3" from ngx-bar-rating@2.0.0
npm ERR! node_modules/ngx-bar-rating
npm ERR!   ngx-bar-rating@"^2.0.0" from the root project
```

#### What is the use-case or motivation for the new feature?
Support for Angular 11 projects.

#### Which versions are you using for the following packages?

ngx-bar-rating: 2.0.0

#### Is there anything else we should know?
Very useful project, thank you!

**Comment by MurhafSousli** [comment]
Will jump to Angular 13 instead in #74
