### ISSUE TITLE
how to Add a min attribute

### ISSUE THREAD

**Issue by faigy111** [MurhafSousli/ngx-bar-rating#61]
I am using your rating bar on my website 
is there any way I could change the min from 1 to 0.
I feel that it is an important feature not only for me.
it does not work for me that the user will leave the bar empty- because my bar is in a form & the form will only be valid when all the fields are valid- touched.
thank you

**Comment by faigy111** [comment]
i worked it out

**Comment by Pulkit-inn** [comment]
Hi @faigy111 @MurhafSousli Can you please share some details on how you achieve this? This will be really helpful if we can add some details in the Package document for the same.
Thanks in advance!!!

**Comment by Pulkit-inn** [comment]
I have fixed this by overriding the below css changes:
```
.br-units {
    counter-reset: counter -1;
}
```
Just in case, if anyone faces a similar issue.
