### ISSUE TITLE
No output to browser when implementing this library

### ISSUE THREAD

**Issue by sterichards** [MurhafSousli/ngx-bar-rating#63]
#### I am submitting a

- [x] Bug Report

#### What is the expected behavior?
Should at least display something

#### What is the current behavior?
No output to browser

#### What are the steps to reproduce?
 - npm i ngx-bar-rating
 Add 'BarRatingModule' to root module imports

Add this to the view
<bar-rating [rate]=5 [max]="5"></bar-rating>

#### Which versions are you using for the following packages?

@angular-devkit/architect       0.900.7
@angular-devkit/build-angular   0.1001.7
@angular-devkit/core            9.0.7
@angular-devkit/schematics      10.2.3
@angular/cdk                    10.2.7
@angular/cli                    10.2.3
@angular/fire                   5.4.2
@angular/material               10.2.7
@schematics/angular             10.2.3
@schematics/update              0.1002.3
rxjs                            6.6.6
typescript                      4.0.7
"ngx-bar-rating": "^2.0.0",

#### Is there anything else we should know?
No errors in browser console

**Comment by salah-yousef** [comment]
I have the same problem with angular 11

**Comment by MurhafSousli** [comment]
It works in Angular 11 https://stackblitz.com/edit/ngx-bar-rating, can you reproduce your issue in a stackblitz?

**Comment by AndreasHerz** [comment]
Maybe you forgot to import the theme?

**Comment by dlugasnyy** [comment]
@MurhafSousli  I have the same isssue. After installation of your package nothing happens in a browser, only empty space appears. ( angular version in proejct is 11)

**Comment by MurhafSousli** [comment]
@AndreasHerz answered the issue

**Comment by lucca-biagi-pag** [comment]
For those who are facing this problem, I'd suggest to check if the styles are imported on angular.json (this part was missing in my scenario, so I just copied from the stackblitz example)

**Comment by timonjagi** [comment]
Thanks @LuccaPrado. Works for Ionic 7/Angular 16
