### ISSUE TITLE
Unable to show fractional value like 3.7 or 4.2

### ISSUE THREAD

**Issue by Jeetu-Gupta** [MurhafSousli/ngx-bar-rating#64]
it's only show half and full star rating. it's not able to show 3.7 or 4.2 something rating in star.

I have used 'fontawesome-o' also.
 
@import '~ngx-bar-rating/themes/br-fontawesome-o-theme'; 

[theme]="'fontawesome-o'"

![image](https://user-images.githubusercontent.com/34885605/119094320-822a3c00-ba2e-11eb-93fc-1298cab3267a.png)

is there any way to show that value?

**Comment by MurhafSousli** [comment]
No, currently there is no way to do it
