### ISSUE TITLE
Angular 12

### ISSUE THREAD

**Issue by Crypt0Graphic** [MurhafSousli/ngx-bar-rating#65]
It works with force option:

`npm i ngx-bar-rating --force`

But need update for proper way. I guess it's not hard work due to error:

```
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^10.1.3" from ngx-bar-rating@2.0.0
```

**Comment by morilon** [comment]
Couldn't we do that? I mean, there's nothing much to change.

**Comment by MurhafSousli** [comment]
Will jump to Angular 13 instead in #74
