### ISSUE TITLE
bar-rating is not a known element

### ISSUE THREAD

**Issue by iArnoldo** [MurhafSousli/ngx-bar-rating#89]
#### I am submitting a
- [x] Bug Report
So somehow the ngx-bar-rating is not getting recognized.
I installed it properly (as instructed) imported in the NgModule where he finds it and there are no errors.
Now i get the follow error in my template file: 
![image](https://user-images.githubusercontent.com/15922858/195133698-9f1112fb-771c-4f51-8eee-1ff2821db9dc.png)

What i also found is this:
![image](https://user-images.githubusercontent.com/15922858/195134099-623dbc80-4caa-4c3a-bb06-881ac76e10a5.png)
Has anyone experienced this?

#### Which versions are you using for the following packages?

Angular: 10.1.6
ngx-bar-rating: 3.0.0

**Comment by MurhafSousli** [comment]
You probably import it in the wrong module, maybe you need to import it in the same module where you component is declared.
