### ISSUE TITLE
rateChange is automatically called when page is loaded.

### ISSUE THREAD

**Issue by amdani786** [MurhafSousli/ngx-bar-rating#90]
When we load the page the bar rating values get binded and rateChange is automatically  being called. We only want to call when user manually change the bar rating. Is there any other event available?

**Comment by BenPKore** [comment]
I'm running into this issue as well. Using the bar-rating input inside a stepper. Any solution?

**Comment by MurhafSousli** [comment]
Please add a reproduction stackblitz https://stackblitz.com/edit/ngx-bar-rating

**Comment by BenPKore** [comment]
Here is how we are currently implementing the bar-rating: https://stackblitz.com/edit/ngx-bar-rating-ymcvcm?file=src/app/app.component.html

**Comment by MurhafSousli** [comment]
Published v7.0.0, this should be fixed, please feel free to reopen if you are still having the issue.
